services:
  reverse_proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx
    depends_on:
      - valuator_1
      - valuator_2
    ports:
      - "8080:8080"
    networks:
      - valuator

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - valuator
  
  rabbitmq:
    image: rabbitmq:3.13.7-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - valuator

  valuator_1:
    container_name: valuator_1
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    environment:
      urls: "http://0.0.0.0:5001"
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "5001:5001"
    networks:
      - valuator

  valuator_2:
    container_name: valuator_2
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    environment:
      urls: "http://0.0.0.0:5002"
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "5002:5002"
    networks:
      - valuator

  rank_calculator_1:
    container_name: rank_calculator_1
    build:
      context: .
      dockerfile: RankCalculator/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - valuator

networks:
  valuator:
    driver: bridge