worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format valuator_format
        '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        'upstream=$upstream_addr '
        'upstream_status=$upstream_status';
    access_log /dev/stdout valuator_format;
    access_log /dev/stderr warn
    access_log /var/log/nginx/access_log valuator_format;
    error_log /var/log/nginx/error.log warn;

    sendfile on;

    # Список серверов, куда будут проксироваться запросы.
    # Подробности по ссылке:
    # https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
    upstream backend {
        server valuator_1:5001;
        server valuator_2:5002;
        server valuator_3:5003;
    }

    # 8080 порт - точка входа для пользователей
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;
        }
    }
}
